apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iq922xgw3-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iq922xgw3-go 
  name: iq922xgw3-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iq922xgw3-go 
